/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CenterContainer: typeof import('./src/components/HeaderBar/children/CenterContainer.vue')['default']
    Channel: typeof import('./src/components/HeaderChannel/children/Channel.vue')['default']
    ChannelFixed: typeof import('./src/components/HeaderChannel/children/ChannelFixed.vue')['default']
    ColorPicker: typeof import('./src/components/color/ColorPicker.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeaderBar: typeof import('./src/components/HeaderBar/index.vue')['default']
    HeaderChannel: typeof import('./src/components/HeaderChannel/index.vue')['default']
    LeftEntry: typeof import('./src/components/HeaderBar/children/LeftEntry.vue')['default']
    LoadingBuff: typeof import('./src/components/PlayerWrapper/LoadingBuff.vue')['default']
    Login: typeof import('./src/components/Login/index.vue')['default']
    LoginRegister: typeof import('./src/components/LoginRegister/index.vue')['default']
    MsgPopover: typeof import('./src/components/Popover/MsgPopover.vue')['default']
    PlayerLoading: typeof import('./src/components/PlayerWrapper/PlayerLoading.vue')['default']
    PlayerProgress: typeof import('./src/components/PlayerWrapper/PlayerProgress.vue')['default']
    PlayerWrapper: typeof import('./src/components/PlayerWrapper/index.vue')['default']
    Popover: typeof import('./src/components/Popover/index.vue')['default']
    PopoverUser: typeof import('./src/components/HeaderBar/children/PopoverUser.vue')['default']
    RecommendedSwipe: typeof import('./src/components/RecommendedSwipe/index.vue')['default']
    RightEntry: typeof import('./src/components/HeaderBar/children/RightEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderColumn: typeof import('./src/components/slider/SliderColumn.vue')['default']
    SliderRow: typeof import('./src/components/slider/SliderRow.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    VideoSkeleton: typeof import('./src/components/VideoSkeleton/index.vue')['default']
    VPopover: typeof import('./src/components/Popover/VPopover.vue')['default']
  }
}
