/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CenterContainer: typeof import('./src/components/HeaderBar/children/CenterContainer.vue')['default']
    CenterContent: typeof import('./src/components/HeaderBar/children/CenterContent.vue')['default']
    ChannelFiexd: typeof import('./src/components/HeaderChannel/children/channelFiexd.vue')['default']
    ChannelFiexl: typeof import('./src/components/HeaderChannel/children/channelFiexl.vue')['default']
    ChannelFixed: typeof import('./src/components/HeaderChannel/children/ChannelFixed.vue')['default']
    ColorPicker: typeof import('./src/components/color/ColorPicker.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HeaderBar: typeof import('./src/components/HeaderBar/index.vue')['default']
    HeaderChannel: typeof import('./src/components/HeaderChannel/index.vue')['default']
    LeftEntry: typeof import('./src/components/HeaderBar/children/LeftEntry.vue')['default']
    LoadingBuff: typeof import('./src/components/PlayerWrapper/LoadingBuff.vue')['default']
    PlayerLoading: typeof import('./src/components/PlayerWrapper/PlayerLoading.vue')['default']
    PlayerProgress: typeof import('./src/components/PlayerWrapper/PlayerProgress.vue')['default']
    PlayerWrapper: typeof import('./src/components/PlayerWrapper/index.vue')['default']
    RecommendedSwipe: typeof import('./src/components/RecommendedSwipe/index.vue')['default']
    RightEntry: typeof import('./src/components/HeaderBar/children/RightEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderColumn: typeof import('./src/components/slider/SliderColumn.vue')['default']
    SliderRow: typeof import('./src/components/slider/SliderRow.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    VideoSkeleton: typeof import('./src/components/VideoSkeleton/index.vue')['default']
  }
}
